name: CI

on:
  push:
    branches:
      - github-action
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
      projectKey: your_project_key
      organization: your_organization
      env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}